### ISSUE TITLE
PGF 4.0 Wishes / feedback

### ISSUE THREAD

**Issue by Fleymour** [0xbs/premade-groups-filter#181]
cool that you bring an update thats now have similarity in UI to the windtools M+ thing. 
sadly this update lost alot of features i was using on daily bases for years! 

biggest issue / wish:
-> i was a big fan to filter the groups by members / have heals / have tanks / max 2 dps etc... the  "partyfit" options cant combine all those features.. would be cool to have these back as option to enable further / old Filters (sure i can  type it in the advanced area.. but bringing back old "buttons" are a far easier / better feature )

wish:
-> i am the person that tyed for years the dungeons i DONT want to see .. would be cool to invert the dungeon select in the options.
-> some old groupfinder weakauras are used to sort by rio / show rio / hide groups below m+ rating and more would be cool to add more features in the options for this (i could send you multiple weakauras / links to show what these can do) 
-> i dont like stacking same dps ( same dps class than me) so i often filtered these groups.. maybe a button to enable this would be cool. i mean 2 dps DH, warriors, mages, hunters arent a gain for the group.  maybe people think same as me here.

**Comment by 0xbs** [comment]
Thanks for the feedback! I pushed 4.0.0 to see what players think because I rarely get feedback and I don't really know how you guys are using the addon. Some questions:

1. Did you use the Members filter? Or just Tanks/Heals/DPS?
2. What do you think about brfit, blfit, not declined? Useful or scrap it for tanks/heals/dps?
3. Groups are sorted by M+ rating by default, there is no WeakAura needed. You can already filter by M+ rating, it's the second filter option. Is there anything else that is really important?
4. Excluding two dungeons is the same as ticking 6 dungeon boxes, which is still okay-ish. To keep the UI simple, I would keep it like this for now. I might add an "invert"-Checkbox that make all boxes exclude.

**Comment by dino-kung** [comment]
The new interface looks awesome , and the new blfit and brfit are also awesome .. 
how ever something is probably broke there , cause for example , I choose not to see the underot , but it still shows.
I tried to use the filter by typing the code ( and not(undr)) still didnt work.
update , it sometimes works !
Anyway , great work , best addon ever

**Comment by Fleymour** [comment]
> * Did you use the Members filter? Or just Tanks/Heals/DPS?
> * What do you think about brfit, blfit, not declined? Useful or scrap it for tanks/heals/dps?
> * Groups are sorted by M+ rating by default, there is no WeakAura needed. You can already filter by M+ rating, it's the second filter option. Is there anything else that is really important?
> * Excluding two dungeons is the same as ticking 6 dungeon boxes, which is still okay-ish. To keep the UI simple, I would keep it like this for now. I might add an "invert"-Checkbox that make all boxes exclude.

1. depends for raids ill use member filter mostly due to bigger raids = more loot :D sometimes for m+ too but rarely.. there more the tank or healer filter because at some days / times these roles getting rar / hard to kill.
2. brfit and blfit are great. i didnt used / Know them for a long time and i like it because you literally want these anyway in every key. would help alot of people -> must have!  not declined : not needed really due to the recolor of group names if declined... rather bring back the member filter .. that use people alot (as far i saw in some streams etc)
3.  oke whens default filtered thats fine i guess. ah btw here is the weakaura alot of players still use (yeah its old) https://wago.io/klC4qqHaF 
4. ah yeah.. as i said i am used to blacklist the dungeons ill need.. ill can work with current feature.. a invert is just a nice to have surely :)

**Comment by 0xbs** [comment]
No problem, I will put it back :) That's all valuable feedback, that's why we talk. Players were begging me to put dungeon checkboxes and some suggested that partyfit is actually more useful than alle the other filters. Never got any other feedback and I am using partyfit a lot myself, so I changed it.

**Comment by Fleymour** [comment]
not sure to if the m+ partyfit interfere with the member / tank / healer / dps  filter.. or maybe the partyfit will deactivate these...  but yeah you will know better :) 

thanks for working on this :)

**Comment by 0xbs** [comment]
Okay version 4.0.1 is out. I hope this resolves most of your issues.

Blacklist dungeons not yet implemented. Thinking about an option to toggle the dungeon column.

**Comment by lholbert** [comment]
>>> Did you use the Members filter? Or just Tanks/Heals/DPS?
-YES especially in raids to filter out ads (members must be at least 2)

>>> What do you think about brfit, blfit, not declined? Useful or scrap it for tanks/heals/dps?
-Even though I play classes for brfit and blfit, I'd never use those.
-"not declined" has been part of my standard advanced filter expression for ages (raid and dungeon)

>>> Groups are sorted by M+ rating by default, there is no WeakAura needed. You can already filter by M+ rating, it's the second filter option. Is there anything else that is really important?
-Not for me

>>> Excluding two dungeons is the same as ticking 6 dungeon boxes, which is still okay-ish. To keep the UI simple, I would keep it like this for now. I might add an "invert"-Checkbox that make all boxes exclude.
-I relly like the new dungeon checkboxes, I'm perfectly ok with the way they work now.

In general, I love the new structure of the filters, I've gone from almost 100% advanced filter usage to practically none (just region and declined).

REQUEST
Any chance to incorporate the region plugin as a built in?  Would that filter on the first pass so say for instance OCE would never showup (with the current architecture it takes a "refresh" to filter them).

**Comment by dstaller** [comment]
Liking the new changes (though the newest one with adding the members/roles while keeping the dungeon ticks make the window a bit wide but not sure what else could be improved to slim it down and keep people happy).

My only concern is that prior to this 4.0 both raid and dungeons were being sorted by leader IO (I assume this was being done using the WA that the other guy linked above). It still works for dungeons, but for some reason it isn't being sorted in the raid section the same way but it works when disabling the addon. Any way to fix this so scrolling to the bottom isn't necessary to find potentially better groups?

**Comment by 0xbs** [comment]
> prior to this 4.0 both raid and dungeons were being sorted by leader IO

But is a good M+ runner a good raid leader? Wouldn't it be better to sort it by progress and number of clears?

> I assume this was being done using the WA that the other guy linked above

This was a feature of PGF, no WeakAura needed. I changed it because a M+ rating says not much about raiding skills.

**Comment by dstaller** [comment]
Does it actually sort that way currently though? I mean sorting by raid progression seems like a good idea, but it doesn't feel like it's currently doing that. I usually sort by M+ rating simply because more people with higher rating are likely to have better prog than people with low rating so it was just an easier way to start from top to bottom without scrolling to the bottom to find the guy with decent raid experience leading a pug. I'd happily take anything that sorts better players at top and worse players at bottom though honestly.

**Comment by 0xbs** [comment]
It sorts raids at the moment by the Blizz sorting (partyfit, friends, age). 

I probably should add some default sorting by mprating or provide a dropdown to select the desired sorting.

**Comment by dstaller** [comment]
Yea I mean any type of sorting that puts better groups at top would be ideal but blizzard's default sorting is kind of inconvenient for quickly finding good groups. Whether it's M+ rating or raid progress I feel like many people would agree that they prefer that kind of sorting. As it stands I'm having to check off PGF for raids so that I'm not all over the place mousing over every group trying to find the type of group I'm looking for. Even if it means just basing it off how it was prior to this overhaul as WA's were able to still sort beforehand without interfering with PGF. Much appreciated for listening though!
